processing:
  analytics:
    stop_on_errors: false
requirements:
  input:
    commit_interval:
      begin: FILES
      end: FILES
    default_language: sv_FI
    dependency_notation:
    - Solved by
    directory: requirements
    txtfile:
      reqtag:
        max_line_lenght: 5000
  inventors:
  - Jenny Lindholm
  - Janne Holm
  stakeholders:
  - development
  - management
  - users
  - customers
topics:
  ts_common:
    sources:
    - - git
      - start_vers: 9ca60c81cd91ab42597a7e892353f70cc57720b8
        end_vers: HEAD
        requirements_dirs:
        - requirements
        topics_dirs:
        - topics
        topic_root_node: ReqsDocument
        constraints_dirs:
        - constraints
        txtfile:
          reqtag:
            max_line_lenght: 5000
    output:
      graph:
      - output_filename: artifacts/req-graph1.dot
      graph2:
      - output_filename: artifacts/req-graph2.dot
      html:
      - footer: html/footer.html
        header: html/header.html
        output_directory: artifacts/html
      latex2:
      - output_filename: artifacts/reqtopics.tex
      prios:
      - output_filename: artifacts/reqsprios.tex
      stats_burndown1:
      - output_filename: artifacts/stats_burndown.csv
        start_date: '2020-03-01'
      stats_reqs_cnt:
      - output_filename: artifacts/stats_reqs_cnt.csv
      stats_sprint_burndown1:
      - output_filename: artifacts/stats_sprint_burndown.csv
        start_date: '2020-03-01'
      version1:
      - output_filename: artifacts/reqs-version.txt
